/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.demo.view.Panels;

import com.mycompany.demo.EcommerceT1LpApplication;
import com.mycompany.demo.controller.SessionController;
import com.mycompany.demo.entities.Product;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author alunolages
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seeCartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addToCart1 = new javax.swing.JButton();
        addToCart2 = new javax.swing.JButton();
        addToCart3 = new javax.swing.JButton();
        quantity1 = new javax.swing.JSpinner();
        quantity2 = new javax.swing.JSpinner();
        quantity3 = new javax.swing.JSpinner();

        seeCartBtn.setText("See cart");
        seeCartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeCartBtnMouseClicked(evt);
            }
        });

        jLabel1.setText("Item1");

        jLabel2.setText("Item2");

        jLabel3.setText("Item3");

        addToCart1.setText("Add to Cart");
        addToCart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCart1MouseClicked(evt);
            }
        });

        addToCart2.setText("Add to Cart");
        addToCart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCart2MouseClicked(evt);
            }
        });

        addToCart3.setText("Add to Cart");
        addToCart3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCart3MouseClicked(evt);
            }
        });

        quantity1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seeCartBtn)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(addToCart1)
                        .addGap(107, 107, 107)
                        .addComponent(addToCart2)
                        .addGap(97, 97, 97)
                        .addComponent(addToCart3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(quantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(quantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToCart1)
                    .addComponent(addToCart2)
                    .addComponent(addToCart3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(seeCartBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToCart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCart1MouseClicked
        int quantity = (int) quantity1.getValue();
        addToCart(EcommerceT1LpApplication.mainFrame.productController.findById(1l), quantity);
    }//GEN-LAST:event_addToCart1MouseClicked

    private void addToCart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCart2MouseClicked
        int quantity = (int) quantity2.getValue();
        addToCart(EcommerceT1LpApplication.mainFrame.productController.findById(2l), quantity);
    }//GEN-LAST:event_addToCart2MouseClicked

    private void addToCart3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCart3MouseClicked
        int quantity = (int) quantity3.getValue();
        addToCart(EcommerceT1LpApplication.mainFrame.productController.findById(3l), quantity);
    }//GEN-LAST:event_addToCart3MouseClicked

    private void seeCartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeCartBtnMouseClicked
        JFrame window = (JFrame) SwingUtilities.getWindowAncestor(this);
        EcommerceT1LpApplication.mainFrame.changeWindow(window, this, EcommerceT1LpApplication.mainFrame.cartPanel);
        EcommerceT1LpApplication.mainFrame.cartPanel.startTable();
    }//GEN-LAST:event_seeCartBtnMouseClicked

    public void addToCart(Product product, Integer quantity) {
        EcommerceT1LpApplication.mainFrame.cartController.addProductToCart(product, quantity, SessionController.getInstance());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart1;
    private javax.swing.JButton addToCart2;
    private javax.swing.JButton addToCart3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner quantity1;
    private javax.swing.JSpinner quantity2;
    private javax.swing.JSpinner quantity3;
    private javax.swing.JButton seeCartBtn;
    // End of variables declaration//GEN-END:variables
}
